### ISSUE TITLE
failed to set audit PID: file exists

### ISSUE THREAD

**Issue by varunsh-coder** [elastic/go-libaudit#121]
I have been using go-libaudit/v2 to monitor network and file events on GitHub Actions runners. 

The project is at https://github.com/step-security/harden-runner and https://github.com/step-security/agent and the code that uses go-libaudit/v2 is here: https://github.com/step-security/agent/blob/9d3f70b3123baaf6b4b2372ca7ba7109c0aebfaf/procmon_linux.go#L19

The code was working fine until a day back when GitHub Actions Ubuntu 20.04.4 VM was updated to use kernel 5.15. 

Now the `receive` method at https://github.com/step-security/agent/blob/9d3f70b3123baaf6b4b2372ca7ba7109c0aebfaf/procmon_linux.go#L113 does not receive any events. The `MonitorProcesses` method runs without any errors, just no events are received after it. 

Interestingly, using the Ubuntu 22.04 VM with kernel 5.15 works. This table shows the environments where the code works and where it doesn't work

|Kernel   | Ubuntu Version | Works?|
|--------|----------------|-------|
| 5.13      |  20.04.4            | Yes     |
| 5.15      |  20.04.4            | No      |
| 5.15      |  22.04               | Yes     |

Please let me know if you have ideas on how I can troubleshoot and fix this issue?

**Comment by varunsh-coder** [comment]
I did some more digging. The code I am using is based off of https://github.com/elastic/go-libaudit/blob/7f33cdde531eab250a04bfe04c1fc3d7ca231550/cmd/audit/audit.go

When I modified below code to use `libaudit.WaitForReply`, I got an error `failed to set audit PID: file exists`

https://github.com/elastic/go-libaudit/blob/7f33cdde531eab250a04bfe04c1fc3d7ca231550/cmd/audit/audit.go#L126

I believe this means some other process is already registered to listen. I then printed the process details and it is `/opt/microsoft/auoms/bin/auomscollect`. 

Do you have guidance on how to deal with scenario where another process is already listening? I cannot use multicast listener as I need to modify the rules. Thanks!

**Comment by andrewkroh** [comment]
> I cannot use multicast listener as I need to modify the rules. Thanks!

You should be able to use a multicast listener even if you need to modify the rules. There's no limitation in go-libaudit that would prevent this.
