### ISSUE TITLE
execveCmdLine improperly hex-decodes values which are not hex encoded

### ISSUE THREAD

**Issue by sfines** [elastic/go-libaudit#13]
Given the following input: 
`type=EXECVE msg=audit(1507304439.922:1865): argc=5 a0="useradd" a1="-u" a2="3005" a3="-m" a4="trainer5"`

The execveCmdLine func decodes a2 as 0\x05 which is invalid: 3005 is, in fact the value that should be returned. 

execveCmdLine should check to see if the returned value is in the printable range or in the following character classes: digit, alpha, punct, or space

**Comment by andrewkroh** [comment]
Thanks for reporting this. We should get this added to the log samples in auparse/testdata. And enhance the hex to ASCII conversion with a post-decode check as you have described. Would you be interested in opening a PR?

**Comment by andrewkroh** [comment]
The hex encoded argument values are not quoted. So I will investigate make a change that uses this as a cue. In the messages below notice how the second message's `a2` value is not quoted.

```
type=EXECVE msg=audit(1491863086.221:1050925): argc=5 a0="grep" a1="--color=auto" a2="-e" a3="[:alpha:]" a4="/etc/passwd"
type=EXECVE msg=audit(1491946471.575:1075898): argc=3 a0="jq" a1="." a2=7B0A202020202020202022646576223A202230383A3031222C0A202020202020202022696E6F6465223A20223139353439363436222C0A2020202020202020226974656D223A202230222C0A2020202020202020226D6F6465223A202230313030373735222C0A2020202020202020226E616D65223A20222F7573722F62696E2F6A71222C0A2020202020202020226F626A223A2022756E636F6E66696E65645F753A6F626A6563745F723A757365725F686F6D655F743A7330222C0A2020202020202020226F626A74797065223A20224E4F524D414C222C0A2020202020202020226F676964223A202231303031222C0A2020202020202020226F756964223A202231303030222C0A2020202020202020227261775F6D657373616765223A2022617564697428313439313934363239362E3735373A31303735383334293A206974656D3D30206E616D653D5C222F7573722F62696E2F6A715C2220696E6F64653D3139353439363436206465763D30383A3031206D6F64653D30313030373735206F7569643D31303030206F6769643D3130303120726465763D30303A3030206F626A3D756E636F6E66696E65645F753A6F626A6563745F723A757365725F686F6D655F743A7330206F626A747970653D4E4F524D414C222C0A20202020202020202272646576223A202230303A3030222C0A2020202020202020227265636F72645F74797065223A202250415448222C0A20202020202020202273657175656E6365223A20313037353833340A2020202020207D
```

Additionally, the kernel only encodes values with upper-case hex. So we can omit decoding data that contains lower-case characters.

I investigated an approach that checks if the decoded data contains special characters (as per [audit_string_contains_control()](https://github.com/linux-audit/audit-kernel/blob/bebc6082da0a9f5d47a1ea2edc099bf671058bd4/kernel/audit.c#L1907-L1920)), but that isn't sufficient to handle all cases.
