### ISSUE TITLE
Stop using event.type as `stop`

### ISSUE THREAD

**Issue by haesbaert** [elastic/go-libaudit#157]
This is related to https://github.com/elastic/integrations/pull/10090#pullrequestreview-2102410626 and https://github.com/elastic/sdh-beats/issues/4763

As @andrewkroh noticed, it seems there are cases where we should be using `end` instead of `stop`.

**Comment by andrewkroh** [comment]
Fixed by https://github.com/elastic/go-libaudit/pull/159.
