### ISSUE TITLE
id_lookup cache timeout ought to be configurable

### ISSUE THREAD

**Issue by vanveele** [elastic/go-libaudit#24]
ID lookup cache timeout is a fixed constant here:
    https://github.com/elastic/go-libaudit/blob/master/aucoalesce/id_lookup.go#L24
When running Auditbeat, this continuous lookup generates quite a bit of load on a busy host. A configurable value, either globally configurable or optionally passed at lookup time, appears to drop resource usage considerably.

**Comment by andrewkroh** [comment]
I agree. Would you want to open up a PR to fix this? I would change `NewUserCache()` to accept the timeout as a parameter.

**Comment by vanveele** [comment]
Sure. I'll take a look at extending NewUserCache() and NewGroupCache().
