### ISSUE TITLE
The  testRule in audit_test.go is got by calling what functions?

### ISSUE THREAD

**Issue by dongzi88** [elastic/go-libaudit#43]
Hi, May I ask that the testRule in audit_test.go is got by calling what functions? Can you give a small example? Thank you very much!

**Comment by andrewkroh** [comment]
The test contains code that dumps each rule to base64 by using [GetRules](https://godoc.org/github.com/elastic/go-libaudit#AuditClient.GetRules).

https://github.com/elastic/go-libaudit/blob/ec7a7253716958d85ea854cbef4aaffcd6cbd50b/audit_test.go#L136-L149
