### ISSUE TITLE
Update allowed fields with "exclude" flag

### ISSUE THREAD

**Issue by dvas0004** [elastic/go-libaudit#78]
Referring to https://github.com/elastic/go-libaudit/blob/master/rule/rule.go#L623, should the fields **dir** and **path** also be added to the allowed list? These seem to be supported on most kernels.

**Comment by andrewkroh** [comment]
The `exe` field should be allowed too based on https://github.com/torvalds/linux/commit/29c1372d6a9b872acf479ba2744e4e7f043981c0#diff-9e58d9929a3d1403a3f6fd9bd8d775d7b4946bafd9c1bae8b2749bfcb01c9369.

**Comment by andrewkroh** [comment]
`dir` and `path` should not be added to the exclude list. They are not supported by the kernel. This is what is supported by the kernel: https://github.com/torvalds/linux/blob/df0cc57e057f18e44dac8e6c18aba47ab53202f9/kernel/auditfilter.c#L1344-L1377.

To exclude files or directories you can use an `exit` rule.

```
# Ignore /etc/foo.
-a never,exit -S all -F path=/etc/foo

# Monitor changes in /etc.
-w /etc -p wxa
```
